// Item
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const SET_EDIT_ITEM = "SET_EDIT_ITEM";
export const UPDATE_EDIT_ITEM_TITLE = "UPDATE_EDIT_ITEM_TITLE";
export const UPDATE_EDIT_ITEM_NOTE = "UPDATE_EDIT_ITEM_NOTE";
export const UPDATE_EDIT_ITEM_TIME = "UPDATE_EDIT_ITEM_TIME";
export const UPDATE_EDIT_ITEM_CATEGORY = "UPDATE_EDIT_ITEM_CATEGORY";
export const UPDATE_EDIT_ITEM_DIVIDE = "UPDATE_EDIT_ITEM_DIVIDE";
// Item Category
export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
